// <auto-generated />
namespace QLKTX_API_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mydb310301 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mydb310301));
        
        string IMigrationMetadata.Id
        {
            get { return "202003310450391_mydb310301"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
