// <auto-generated />
namespace QLKTX_API_V2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class mydb3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mydb3));
        
        string IMigrationMetadata.Id
        {
            get { return "202005060830429_mydb3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
